dashboard/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^get_volumen_de_ventas/$',
        views.get_volumen_de_ventas, name='get_volumen_de_ventas'),
    url(r'^get_existencia_final/$',
        views.get_existencia_final, name='get_existencia_final'),
    url(r'^get_ventas/$', views.get_ventas, name='get_ventas'),
    url(r'^get_ventas_aditivos/$', views.get_ventas_aditivos,
        name='get_ventas_aditivos'),
    url(r'^get_controllers_data/$', views.get_controllers_data,
        name='get_controllers_data'),
    url(r'^get_totales_data/$', views.get_totales_data,
        name='get_totales_data'),
    url(r'^get_existencias_data/$', views.get_existencias_data,
        name='get_existencias_data')

    ]

djcontroller/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'', include('dashboard.urls')),
    url(r'^admin/', admin.site.urls),
]

dashboard/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or
# field names.
from __future__ import unicode_literals
from django.db import models

class SaleOrderLine(models.Model):
    create_date = models.DateTimeField(blank=True, null=True)
    qty_to_invoice = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    sequence = models.IntegerField(blank=True, null=True)
    price_unit = models.DecimalField(max_digits=65535, decimal_places=65535)
    product_uom_qty = models.DecimalField(max_digits=65535, decimal_places=65535)
    qty_invoiced = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    #write_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='write_uid', blank=True, null=True)
    #currency = models.ForeignKey('ResCurrency', models.DO_NOTHING, blank=True, null=True)
    #create_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='create_uid', blank=True, null=True)
    price_tax = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    #product_uom = models.ForeignKey('ProductUom', models.DO_NOTHING, db_column='product_uom')
    customer_lead = models.FloatField()
    #company = models.ForeignKey('ResCompany', models.DO_NOTHING, blank=True, null=True)
    name = models.TextField()
    state = models.TextField(blank=True, null=True)
    #order_partner = models.ForeignKey('ResPartner', models.DO_NOTHING, blank=True, null=True)
    #order = models.ForeignKey('SaleOrder', models.DO_NOTHING)
    price_subtotal = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    discount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    write_date = models.DateTimeField(blank=True, null=True)
    price_reduce = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    qty_delivered = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    price_total = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    invoice_status = models.TextField(null=True)
    #product = models.ForeignKey('ProductProduct', models.DO_NOTHING)
    #salesman = models.ForeignKey('ResUsers', models.DO_NOTHING, blank=True, null=True)
    #product_packaging = models.ForeignKey('ProductPackaging', models.DO_NOTHING, db_column='product_packaging', blank=True, null=True)
    #route = models.ForeignKey('StockLocationRoute', models.DO_NOTHING, blank=True, null=True)
    barcode = models.TextField(blank=True, null=True)
    subtotal = models.FloatField(blank=True, null=True)
    turno_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'sale_order_line'


class GobusinessSessions(models.Model):
    #create_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='create_uid', blank=True, null=True)
    #user = models.ForeignKey('ResUsers', models.DO_NOTHING, blank=True, null=True)
    date_end = models.DateTimeField(blank=True, null=True)
    #write_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='write_uid', blank=True, null=True)
    write_date = models.DateTimeField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
    date_init = models.DateTimeField(blank=True, null=True)
    is_active = models.NullBooleanField()
    endday = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'gobusiness_sessions'


class AccountPaymentTerm(models.Model):
    #create_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='create_uid', blank=True, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
    name = models.TextField()
    #company = models.ForeignKey('ResCompany', models.DO_NOTHING)
    #write_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='write_uid', blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    write_date = models.DateTimeField(blank=True, null=True)
    active = models.NullBooleanField()

    class Meta:
        managed = False
        db_table = 'account_payment_term'

    def __str__(self):
        return self.name


class VentasControlador(models.Model):
    create_date = models.DateTimeField(blank=True, null=True)
    omni = models.CharField(max_length=2, blank=True, null=True)
    endday_moved0 = models.CharField(max_length=10, blank=True, null=True)
    nozzle = models.IntegerField(blank=True, null=True)
    ppu = models.DecimalField(
        max_digits=65535, decimal_places=65535, blank=True, null=True)
    transid = models.CharField(unique=True, max_length=8, blank=True, null=True)
    authpos = models.CharField(max_length=2, blank=True, null=True)
    transactionstatus = models.TextField(blank=True, null=True)
    closedby = models.IntegerField(blank=True, null=True)
    fp = models.CharField(max_length=2, blank=True, null=True)
    ft = models.CharField(max_length=4, blank=True, null=True)
    volume = models.DecimalField(
        max_digits=65535, decimal_places=65535, blank=True, null=True)
    pstat = models.CharField(max_length=2, blank=True, null=True)
    endhours = models.CharField(max_length=10, blank=True, null=True)
    write_date = models.DateTimeField(blank=True, null=True)
    attendant = models.IntegerField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    tstat = models.CharField(max_length=2, blank=True, null=True)
    amount = models.DecimalField(
        max_digits=65535, decimal_places=65535, blank=True, null=True)
    endday_moved1 = models.DateField(blank=True, null=True)
    endday = models.TextField(blank=True, null=True)
    #sesion = models.ForeignKey(
    #    'GobusinessSessions', models.DO_NOTHING, blank=True, null=True)
    # Field name made lowercase.
    id_vehiculo_moved0 = models.IntegerField(
        db_column='Id_Vehiculo_moved0', blank=True, null=True)
    # Field name made lowercase.
    cod_empleado = models.IntegerField(
        db_column='Cod_Empleado', blank=True, null=True)
    # Field name made lowercase.
    km_vehiculo = models.TextField(
        db_column='Km_Vehiculo', blank=True, null=True)
    # Field name made lowercase.
    nombre_cliente = models.TextField(
        db_column='Nombre_Cliente', blank=True, null=True)
    # Field name made lowercase.
    codpiloto_moved0 = models.IntegerField(
        db_column='CodPiloto_moved0', blank=True, null=True)
    # Field name made lowercase.
    codcliente = models.TextField(db_column='CodCliente', blank=True, null=True)
    # Field name made lowercase.
    tpago = models.ForeignKey(
        'AccountPaymentTerm', models.DO_NOTHING, db_column='TPago', blank=True,
        null=True)
    #details = models.ForeignKey(
    #    'GobusinessDetailsSale', models.DO_NOTHING, blank=True, null=True)
    existencia = models.FloatField(blank=True, null=True)
    saldo = models.DecimalField(
        max_digits=65535, decimal_places=65535, blank=True, null=True)
    utilidad = models.DecimalField(
        max_digits=65535, decimal_places=65535, blank=True, null=True)
    costo = models.DecimalField(
        max_digits=65535, decimal_places=65535, blank=True, null=True)
    # Field name made lowercase.
    id_vehiculo = models.TextField(
        db_column='Id_Vehiculo', blank=True, null=True)
    # Field name made lowercase.
    codpiloto = models.TextField(
        db_column='CodPiloto', blank=True, null=True)
    existencia_inicial = models.DecimalField(
        max_digits=65535, decimal_places=65535, blank=True, null=True)
    valor_inventario = models.DecimalField(
        max_digits=65535, decimal_places=65535, blank=True, null=True)
    existencia_final = models.DecimalField(
        max_digits=65535, decimal_places=65535, blank=True, null=True)
    precio_promedio = models.DecimalField(
        max_digits=65535, decimal_places=65535, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ventas_controlador'


class RtControlador(models.Model):
    TSTAT_LIST=(
                ('I','Inactivo'),
                ('A','Venta Autorizada'),
                ('B','Ocupado'),
                ('C','Transacción Completada'),
                ('R','Transacción obtenida'),
                ('D','Campo de datos'),
                ('H','Ocupado'),
                ('Z','Autorizado por POS'),
                ('S','Detenido por POS'),
                ('X','Desconectado'),
                )


    PSTAT_LIST=(
                ('i','Inactivo'),
                ('u','Pistola descolgada'),
                ('a','Venta autorizada'),
                ('p','Despachando combustible'),
                ('t','Venta terminada'),
                ('s','Detenido por POS'),
                ('x','Desconectado'),
                ('k','Keypad Preset Pending'),
                )

    FT_LIST = (
                ('*R', 'Regular'),
                ('*D', 'Diesel'),
                ('*S', 'Súper')
                )
    create_date = models.DateTimeField(blank=True, null=True)
    omni = models.CharField(max_length=2, blank=True, null=True)
    endday_moved0 = models.CharField(max_length=10, blank=True, null=True)
    nozzle = models.IntegerField(blank=True, null=True)
    #write_uid = models.ForeignKey('ResUsers', models.DO_NOTHING, db_column='write_uid', blank=True, null=True)
    ppu = models.DecimalField(max_digits=65535, decimal_places=65535,

dashboard/controller.py
from .models import RtControlador, VentasControlador, VolumenVentasControlador
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import connection
from collections import namedtuple
import random


COLORS = [(139, 0, 0),
          (0, 100, 0),
          (0, 0, 139)]

colors = {'*D': '#88C057',
          '*R': '#FFCC66',
          '*S': '#ED7161'}


def random_color():
    return random.choice(COLORS)


def fetch_volument_ventas():
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM volumen_ventas_controlador")
        desc = cursor.description
        nt_result = namedtuple('Result', [col[0] for col in desc])
        for row in cursor.fetchall():
            yield nt_result(*row)


def volumen_de_ventas():
    data = {"min": 0.0,
            "max": 0.0,
            "plot_data": [],
            "labels": ["{0}:00".format(h) for h in range(24)]
            }

    prev_ft = ''
    index = 0

    min_value = 0
    max_value = 0
    for volumen in fetch_volument_ventas():
        if volumen.ft is None:
            break
        if volumen.ft != prev_ft:
            data["plot_data"].append({"label": volumen.ft,
                                      "data": [0,]*24 ,
                                      "backgroundColor": colors[volumen.ft],
                                      "borderColor": colors[volumen.ft],
                                      "strokeColor": colors[volumen.ft],
                                      "fill":False,
                                      })
            #data["colors"].append(colors[volumen.ft])
            prev_ft = volumen.ft
            index = len(data["plot_data"]) - 1

        data["plot_data"][index]["data"][volumen.hour] = volumen.coalesce
            #append([volumen.hour, volumen.coalesce])

        min_value = min(min_value, volumen.coalesce)
        max_value = max(max_value, volumen.coalesce)
    data["min"] = min_value
    data["max"] = max_value
    return data


def fetch_existencia():
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM existencia_final_por_ft")
        desc = cursor.description
        nt_result = namedtuple('Result', [col[0] for col in desc])
        for row in cursor.fetchall():
            yield nt_result(*row)


def existencia_final_por_ft():
    data = []

    for ft in fetch_existencia():
        data.append({"ft": ft.ft,
                     "ft.ft_": ft.ft[1],
                     "existencia_final": ft.existencia_final})

    return data


def fetch_totales_de_ventas():
    with connection.cursor() as cursor:
        cursor.execute("SELECT sum(volume) as volume, sum(amount) as amount "
                       "FROM ventas_controlador WHERE nozzle = 1;")
        desc = cursor.description
        nt_result = namedtuple('Result', [col[0] for col in desc])
        row = nt_result(*cursor.fetchone())
        return row


def totales_de_ventas():

    return fetch_totales_de_ventas()


def fetch_page_ventas(start, length, filter):

    queryset = VentasControlador.objects.only("transid", "fp", "ft", "volume",
                                              "amount", "endhours", "tpago",
                                              "nombre_cliente", "codpiloto",
                                              "id_vehiculo")\
                                         .filter(nozzle=1)\
                                         .order_by('-transid').order_by('-tpago')

    total = queryset.count()
    filtered_total = total
    if filter != '':
        queryset = queryset.filter(transid__contains=filter)
        filtered_total = queryset.count()

    paginator = Paginator(queryset, length)  # Shows only 10 records per page
    page = (start/length + 1)
    try:
        ventas = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        ventas = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 7777), deliver last page of results.
        ventas = paginator.page(paginator.num_pages)
    return ventas, total, filtered_total


def fetch_venta_aditivos(start, length, filter=None):
    with connection.cursor() as cursor:
        cursor.execute("SELECT count(*) FROM gobusiness_sessions"
                       " WHERE is_active = TRUE;")
        total = cursor.fetchone()[0]

        cursor.execute("SELECT s.turno_id, s.name, s.product_uom_qty as quantity, "
                       " s.price_unit, s.Price_total FROM sale_order_line as s "
                       " JOIN (SELECT id FROM gobusiness_sessions "
                       " WHERE is_active = TRUE) as P "
                       " ON s.turno_id = P.id;")
        #total = cursor.count()
        filtered_total = total

        return cursor.fetchall()[start: start+length], total, filtered_total

templates/base.html
{% load static from staticfiles %}
<html lang='es'>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{title}} </title>
        <!-- Bootstrap -->
        <link href="{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}"  rel="stylesheet">
        <!-- Font Awesome -->
        <link href="{% static "vendors/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
        <!-- NProgress -->
        <link href="{% static "vendors/nprogress/nprogress.css" %}" rel="stylesheet">
        <link href="{% static "vendors/pnotify/dist/pnotify.css" %}" rel="stylesheet">
        <!-- iCheck -->
        <link href="{% static "vendors/iCheck/skins/flat/green.css" %}" rel="stylesheet">

        <!-- bootstrap-progressbar -->
        <link href="{% static "vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" %}" rel="stylesheet">
        <!-- JQVMap -->
        <link href="{% static "vendors/jqvmap/dist/jqvmap.min.css" %}" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="{% static "vendors/bootstrap-daterangepicker/daterangepicker.css" %}" rel="stylesheet">

        <!-- Custom Theme Style -->
        <link href="{% static "build/css/custom.css" %}" rel="stylesheet">

        {% block context_script %}
        {% endblock %}

    </head>

    <body>
        <div class="container body">
            <div class="main-container">
                <div class="right_col" role="main" style="min-height: 2027px;">
                    {% block group-controllers %}
                    {% endblock %}
                    {% block details %}
                    {% endblock %}
                    {% block aditivos %}
                    {% endblock %}
                    {% block charts %}
                    {% endblock %}
                </div>
            </div>
        </div>

        <!-- jQuery -->
        <script src="{% static "vendors/jquery/dist/jquery.min.js" %}"></script>
        <!-- Bootstrap -->
        <script src="{% static "vendors/bootstrap/dist/js/bootstrap.min.js" %}"></script>
        <!-- FastClick -->
        <script src="{% static "vendors/fastclick/lib/fastclick.js" %}"></script>
        <!-- NProgress -->
        <script src="{% static "vendors/nprogress/nprogress.js" %}"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="{% static "vendors/moment/moment.js" %}"></script>
        <script src="{% static "vendors/bootstrap-daterangepicker/daterangepicker.js" %}"></script>
        <!-- Chart.js -->
        <script src="{% static "vendors/Chart.js/dist/Chart.min.js" %}"></script>
        <!-- jQuery Sparklines -->
        <script src="{% static "vendors/jquery-sparkline/dist/jquery.sparkline.min.js" %}"></script>
        <!-- Flot -->
        <script src="{% static "vendors/Flot/jquery.flot.js" %}"></script>
        <script src="{% static "vendors/Flot/jquery.flot.pie.js" %}"></script>
        <script src="{% static "vendors/Flot/jquery.flot.time.js" %}"></script>
        <script src="{% static "vendors/Flot/jquery.flot.stack.js" %}"></script>
        <script src="{% static "vendors/Flot/jquery.flot.resize.js" %}"></script>
        <!-- Flot plugins -->
        <script src="{% static "vendors/flot.orderbars/js/jquery.flot.orderBars.js" %}"></script>
        <script src="{% static "vendors/flot-spline/js/jquery.flot.spline.min.js" %}"></script>
        <script src="{% static "vendors/flot.curvedlines/curvedLines.js" %}"></script>
        <!-- DateJS -->
        <script src="{% static "vendors/DateJS/build/date.js" %}"></script>
        <script src="{% static "vendors/pnotify/dist/pnotify.js" %}"></script>


        {% block table_scripts %}
        {% endblock %}

        <script>
            $(document).ready(function() {
                $('.collapse-link').on('click', function() {
                    var $BOX_PANEL = $(this).closest('.x_panel'),
                        $ICON = $(this).find('i'),
                        $BOX_CONTENT = $BOX_PANEL.find('.x_content');

                    // fix for some div with hardcoded fix class
                    if ($BOX_PANEL.attr('style')) {
                        $BOX_CONTENT.slideToggle(200, function(){
                            $BOX_PANEL.removeAttr('style');
                        });
                    } else {
                        $BOX_CONTENT.slideToggle(200);
                        $BOX_PANEL.css('height', 'auto');
                    }

                    $ICON.toggleClass('fa-chevron-up fa-chevron-down');
                });
                {% block call_load_volume_chart %}
                {% endblock %}

                {% block prepare_table %}
                {% endblock %}

    	      });
        </script>


    </body>

</html>

templates/charts.html
{% load dashboard_extras %}
{% load humanize %}
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Resumen de ventas durante el dia por tipo de combustible</h2>
                <!--div class="filter">
                    <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                        <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                        <span>December 30, 2014 - January 28, 2015</span> <b class="caret"></b>
                    </div>
                </div-->
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-9 col-sm-12 col-xs-12">
                    <div class="demo-container" style="height:520px">
                        <div id="chart_volume" class="demo-placeholder">
                            <canvas id="cchart_volume"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

templates/existencias.html
{% load dashboard_extras %}
{% load humanize %}
{% for ft in existencia_final %}
<li class="media event">
  <a class="pull-left border-green profile_thumb">
      <i class="fa fa-industry" style="color:{{ft.ft|ftcolor}};"></i>
  </a>
  <div class="media-body div_ft_{{ft.ft_}}">
      <a class="title" style="color:{{ft.ft|ftcolor}};" href="#">{{ft.ft}}</a>
      <p><strong>{{ft.existencia_final|floatformat:"4"|intcomma}} </strong>  </p>
      <p> <small>galones</small>
      </p>
  </div>
</li>
{% endfor %}

templates/groupcontrollers.html
{% load dashboard_extras %}
{% load humanize %}
<section group-controllers>
<div class="row tile_count">
    {% for controller in controllers %}
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count" id="dfp{{controller.fp}}">
      <span class="count_top"><i class="fa fa-dashboard"></i> fp{{controller.fp}}</span>
      <div class="count" style="color:{{controller.ft|ftcolor}};">{{controller.amount|prepend_dollars}}</div>
      <table class="table table-responsive borderless paddingless" style="font-size:12px;">
      <tr>
          <td class="count_bottom  font-13">Volumen   </td>
          <td class="text-right   font-10" style="color:{{controller.ft|ftcolor}};">{{controller.volume|floatformat:"4"|intcomma}}</td>
      </tr>

      <tr >
          <td class="count_bottom  font-10">Ppu   </td>
          <td class="text-right font-10">{{controller.ppu|prepend_dollars}} </td>
      </p>
      <tr>
          <td class="count_bottom font-10">tstat: </td>
          <td class="text-right font-10"><i class="fa fa-circle" style="color:{{controller.tstat|tstatcolor}};"></i> {{controller.get_tstat_display}} </td>
          <i class="hidden controller_tstat">{{controller.tstat}}|{{controller.get_tstat_display}}|{{controller.fp}}|{{controller.amount|prepend_dollars}}|{{controller.volume|floatformat:"4"|intcomma}}|{{controller.transid}}</i>
      </p>

      <tr>
          <td class="count_botton font-10">ft: </td>
          <td class="text-center font-10"> {{controller.get_ft_display}}</td>
      </p>
      <tr>
          <td class="count_bottom font-10">pstat    </td>
          <td class="text-right font-10"> <i class="fa fa-circle" style="color:{{controller.pstat|pstatcolor}};"></i> {{controller.get_pstat_display}} </td>
      </p>
    </table>






    </div>
    {% endfor %}

</section>

templates/tablelubs.html
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Ventas de aditivos </h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <table id="table_lubs" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Turno</th>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Precio unitario</th>
            <th>Importe</th>
          </tr>
        </thead>

        <tbody>

        </tbody>
      </table>
    </div>
  </div>
</div>

templates/tabletxns.html
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Detalle de ventas </h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <p class="text-muted font-13 m-b-30">
            Detalle de ventas durante el día, use el cuadro para buscar por transaccion
      </p>
      <div class="col-md-3 col-sm-3 col-xs-6">
          <div>
              <div class="x_title">
                <h2>Existencia <small>(en galones)</small></h2>
                <div class="clearfix"></div>
              </div>
              <ul class="list-unstyled top_profiles scroll-view">
                  <section id="existencia_galones">
                      {% include "existencias.html" %}
                  </section>
                  <li>
                      <section id="totales">
                          {% include "totales.html" %}
                      </section>
                  </li>
              </ul>
            </div>
      </div>
      <div class="col-md-8 col-sm-12 col-xs-12">
      <table id="table_ventas" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#Transacción</th>
            <th>Dispensador</th>
            <th>Producto</th>
            <th>Total galones</th>
            <th>Hora</th>
            <th>TPago</th>
            <th>Piloto</th>
            <th>ID vehículo</th>
          </tr>
        </thead>

        <tbody>

        </tbody>
      </table>
  </div>



    </div>

  </div>
</div>

templates/totales.html
{% load dashboard_extras %}
{% load humanize %}

<div class="col-md-6 col-sm-6 col-xs-12 tile div_monto_total">
    <span><strong>Monto Total</strong></span>
    <h2>{{ totales_de_ventas.amount|prepend_dollars }}</h2>
</div>
<div class="col-md-6 col-sm-6 col-xs-12 tile div_volumen_total">
    <span><strong>Volumen</strong></span>
    <h2>{{ totales_de_ventas.volume|floatformat:"4"|intcomma }}</h2>
</div>